### ISSUE TITLE
Fatal error: Call to undefined function pcntl_signal()

### ISSUE THREAD

**Issue by alias1** [gwen001/s3-buckets-finder#1]
```
⇒  php s3-buckets-bruteforcer.php --bucket ~/Desktop/buckets.txt
11 buckets to test.

Fatal error: Call to undefined function pcntl_signal() in /Users/foo/sec/s3-buckets-finder/BucketBruteForcer.php on line 304
```

http://php.net/manual/en/function.pcntl-signal.php

This is using the default php on macOS:

```
⇒  php --version
PHP 5.6.25 (cli) (built: Sep 19 2016 15:45:41)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by gwen001** [comment]
Take a look at your php.ini, sometimes those functions are disabled.

**Comment by alias1** [comment]
Tried: `brew install homebrew/php/php55-pcntl`

But get the following error when trying to run with it:
```
foo@bar:~/sec/s3-buckets-finder|add-dockerfile
⇒  /usr/local/opt/php55/bin/php ./s3-buckets-bruteforcer.php
PHP Warning:  Module 'pcntl' already loaded in Unknown on line 0

Warning: Module 'pcntl' already loaded in Unknown on line 0
PHP Fatal error:  Arrays are not allowed in class constants in /Users/foo/sec/s3-buckets-finder/BucketBruteForcer.php on line 26

Fatal error: Arrays are not allowed in class constants in /Users/foo/sec/s3-buckets-finder/BucketBruteForcer.php on line 26
```

Based on: http://stackoverflow.com/questions/34174511/how-to-install-php-extension-pcntl-on-my-mac-osx/34176698#34176698

**Comment by gwen001** [comment]
Sorry but I will not rewrite my script to fit old PHP versions unless it affords a great value. You can alter it by yourself or upgrade your PHP.

**Comment by alias1** [comment]
I'm not asking you to rewrite it for an old version. I just want to know which version it's written for, and thus what I should be trying to use. In my edit above, I tried it against 7.1 and am still getting issues.

**Comment by gwen001** [comment]
It's not written for a specific version.
Works perfectly with PHP 5.6.30 and PHP 7.0.15, fresh install, no change in php.ini.

**Comment by alias1** [comment]
Cool. I will try 7.0 and see how it goes.
